### ISSUE TITLE
Week_01_Kim_TaeHyeong

### ISSUE THREAD

**Issue by KimTaeHyeong17** [Apptive-dev-10th/Node_js_Study#2]
1. var 과 let 차이점 및 장단점
2. Js 에서 this keyword 조사하기
3. callback function.

1. var 와 let 의 차이점 및 장단점.
    <var 과 let 의 차이점은 scoping 이다> 
    a) var 의 scope 는 가장 가까운 function block(함수단위) 까지이며 
       let 의 scope 는 가장 가까운 enclosing block 까지이다. 
        ex)
        for(var j = 0 ;j < 10; j++) {
            console.log('j',j);
        }
        console.log('after loop j is ',j); //after loop j is 10
        ------------------------------------------------------------
        function counter(){
            for(var i=0; i<10; i++){
                console.log('i',i);
            }
        }
        counter();
        console.log('afer loop i is ', i); //ReferenceError: i is not defined.

    b) 둘다 block 바깥에서 선언되면 global 변수이다. strict mode 에서 var 은 이미 선언된 변수를 다시 선언할 수 있지만 let 은 불가능하다
    ex) 
    let me = 'foo';
    let me = 'bar';  
    --> SyntaxError : Identifier 'me' has already been declared
    var me = 'foo';
    var me = 'bar'; 

    *var 보다 let을 왜쓰냐면 임시적 사각지대(TDZ)떄문에 쓴다. 어떤 변수가
    호출되었을때 블록 안에 같은 이름의 변수가 없으면 상위 블록에서 선언된 같은 이름의 변수를 호출한다.
    하지만 블록 안에서 let 이나 const로 변수 선언이 있었다면 그 이름의 변수는 변수가 선언되기 이전까지의 
    그 블록안에서는 정의되지 않는 변수로 간주된다. 그래서 그냥 let을 쓰는것 같다.

2. js 에서 this keyword 조사하기.
    this 키워드는 강력한 기능임에도 불구하고 쉽게 이해하기 힘든 부분이다.
    Java 에서 this는 클래스로부터 생성되는 인스턴스 중 현재 객체를 의미한다. 
    JS에서는 this 는 함수의 현재 실행 문맥이다. 먼저 4가지의 함수 실행 타입을 알아야 한다.
        ㄱ)함수 실행 : alert('Hello World');
        ㄴ)메소드 실행 : console.log('Hello World');
        ㄷ)생성자 실행 : new RegExp('\d');
        ㄹ)간접 실행 : alert.call(undefined,'Hello World!');
    각각의 타입은 서로 다른 문맥을 가지는데 이 부분에서 개발자들의 예상과 다른 부분이 생긴다.(특히 Strict mode에서)
    
            1)함수실행
                function hello(name){
                    return 'Hello '+name+'l';
                }
                var message = hello('World');
                console.log(message); //=>'Hello World!'
                -->hello('World') 은 함수 실행으로써 hello 표현식 뒤따라 오는 'World' 인자와 함께 함수 객체로 계산됨
            
            2)함수 실행에서의 this는 전역객체이다.
                근데 전역 객체는 뭐지 : 자바 스크립트는 코드를 실행하기 전 최상위에 위치한 전역 객체를 만든다. 
                JS 에서는 코딩을 할때 전역객체를 생략할수있다(screen, navigater, location, document etc)
                함수 실행에서 실행 문맥은 전역객체이다. 
                    ex) 
                    function sum(a,b){
                        console.log(this === window);
                        this.myNumber = 20;
                        return a+b;
                    } // sum() 은 함수 호출이고 sum()에서의 this 는 전역객체이다.
                    sum(15,16); // =>31;
                    window.myNumber;//=>20;
                엄격 모드에서 함수 샐행 에서의 this 는 undefined 이다. 뭔 소린지 모르겠다.
                    ex)
                    function nonStrictSum(a,b){
                        console.log(this===window);
                        return a+b;
                    }//this 는 window 객체
                    function strictSum(a,b){
                        'use strict'; //엄격모드
                        console.log(this === undefined);
                        return a+b;
                    }//this 는 undefined
                    nonStrictSum(5,6); //=>11
                    strictSum(8,12); //=>20
                    
                뭔소리야 ㄹㅇ 1도 모르겠다 그냥 this 안쓰고싶다.
                
                딴거본다

                ㄱ)javascript 는 세가지 영역에서 수행된다.
                    global, function, eval 영역.

                ㄴ)this 키워드는 다음 두가지 조건에 의해 값이 결정된다
                    어떤 영역에서 수행되었는가
                    호출자가 누구인가

                ㄷ)global 객체란
                    자바스크립트가 구동 될 때에는 언제나 global 객체가 존재한다
                    브라우저에서는 window 객체가 그 역할을 하고 있고 nodejs에서는
                    그냥 global object로 불리는 놈이 있다.

                <this 키워드 파악하는 4가지 규칙>
                    1. 기본적으로 this 는 global 객체이다
                    2. function 영역 에서의 this 는 부모 객체이다.(부모의 자식으로서 불렸을때)
                    3. new 연산자로 생성된 function 영역의 this 는 새로 생성된 객체 그 자신이다
                    4. call 혹은 apply 로 호출된 함수의 경우 call, apply 의 첫번째 인자로 명시된 객체이다.

                    

3. callback function 또는 callback 이 무엇인지 조사하기.
    콜백 함수 : 어떤 이벤트가 발생한 후 수행될 함수를 의미한다. --> js 에서 함수는 1급 객체이므로 인자로 함수를 전달할 수 있다. 
    비동기 처리에서 콜백을 사용하지 않게 된다면, 콜백 함수의 과정이 끝나기 전에 다음 프로세스를 진행하게 된다.
    ex)
    > a = [3,1,2]; console.log(a);
    [ 3, 1, 2 ]
    undefined
    > a = [3,1,2]; a.sort(); console.log(a);
    [ 1, 2, 3 ]
    undefined
    > a = [3,1,2];function b(v1,v2){return v2-v1}; a.sort(b); console.log(a);
    [ 3, 2, 1 ]
    undefined
    > a = [3,1,2];function b(v1,v2){return v1-v2}; a.sort(b); console.log(a);
    [ 1, 2, 3 ]
    undefined  
    b라는 함수는 뭘까 --> 어떤값을 앞으로 보낼지 판단할때마다 b호출
    v1과 v2값에 따라 리턴값을 지정
    > a = [3,1,2];function b(v1,v2){console.log('c',v1,v2); return 0}; a.sort(b); console.log(a);
    c 3 1
    c 1 2
    [ 3, 1, 2 ]
    콜백함수 b는 내가 호출하지 않고 나중에 호출 당할 함수이다.
    > a = [3,1,2]; a.sort(function(v1,v2){return v2-v1;}); console.log(a);
    [ 3, 2, 1 ]
    익명함수 사용 sort(내부에 함수 정의)
    --> sort는 인자가 필요한데 그걸 함수를 던져준다.

4. MIME Type 에 대해서 조사하기
    인터넷에 전달되는 파일 포맷과 포맷 컨텐츠를 위한 2부분의 식별자이다.
    nodejs 에서 MIME Type
    >response.writeHead(200, { 'Content-type': 'audio/mp3' });
    <MIME TYPE 예시>
        text/plain, text/html, text/css, text/xml, image/jpeg, image/png
        video/mpeg, audio/mp3 etc...

5. character encoding 종류에 대해서 조사하기.
UNICODE : univerisal character set.
UTF-8 : 1byte to represent characters in ASCII set.
        2bytes for characters in several more alphabetic blocks
        3bytes for the rest of the BMP.
UTF-16 : 2bytes for any character in the BMP
         4bytes for supplementary characters
UFT-32 : 4bytes for all characters.

**Comment by extJo** [comment]
수고링~
