### ISSUE TITLE
Week_01_JangYuri

### ISSUE THREAD

**Issue by JangYuri** [Apptive-dev-10th/Node_js_Study#3]
1. var 와 let 의 차이점 및 장단점.
  - var: function-scoped 로 호이스팅, 재선언 가능
  - let: block-scoped 로 재선언 불가, 재할당 가능

2. js 에서 this keyword 조사하기.
현재 실행 문맥!!! 호출자가 누구냐에 따라 결정된다!!!! 즉, 자신을 호출한 객체를 의미한다. 기본값으로는 window객체를 가리킨다.
* 엄격 모드에서 함수 실행에서의 this는 undefined다.

3. callback function 또는 callback 이 무엇인지 조사하기.
callback function(콜백 함수)란 어떤 이벤트가 발생한 후 수행될 함수를 의미한다.
callback(콜백)이란 다른 코드의 인수로서 넘겨주는 실행 가능한 코드를 말한다.
콜백함수를 주로 볼 수 있는 경우는 Node.js에서 볼 수 있는데, Node.js의 특성상 비동기처리가 많기 때문에 처리의 결과를 프로그래머가 받기 위해서는 콜백함수를 사용하여 시스템이 결과값을 콜백함수를 호출하여 넘겨주기 때문이다.

4. MIME Type 에 대해서 조사하기
클라이언트에게 전송된 문서의 다양성을 알려주기 위한 메커니즘.
Multipurpose Internet Mail Extensions의 약자로 간략히 말하자면 파일 변환을 뜻한다.
MIME는 이메일과 함께 동봉할 파일을 텍스트 문자로 전환해서 이메일 시스템을 통해 전달하기 위해 개발되었다. 현재는 웹을 통해서 여러형태의 파일 전달하는데 쓰이고 있다.

5. character encoding 종류에 대해서 조사하기.
  - UTF (Unicode Transformation Format) : UTF는 유니코드 형태의 문자를 변환하기 위한 공식이다. 유니코드는 4byte 구성되어 있기 때문에 사용하는 코드 범위에 따라서 1~4byte로 변환이 가능하게 된다. 
  - EUC : euc는 extend unix code의 약자로 유닉스에서 영어를 제외한 문자를 표시하기 위한 확장 부호를 의미. 그 중 euc-kr은 한글 표현을 위한 문자 인코딩인데, 영문은 KSC5636(ASCII와 동일하나 역슬래쉬를 원표시로 대체)으로 처리하고 한글은 KSC5601로 처리한다. 과거 euc-kr은 KSC5601-87의 완성형 한글이었으나 현재의 euc-kr은 KSC5601-92로 조합형 한글까지 사용 가능하다.
  - CP949:마이크로소프트에서 사용하는 한글 문자의 부호표이다. 본래 code page는 IBM에서 최초 고안하였으나 MS-window에서 한글 표현을 위해 채용하면서 MS949로 불리우기도 한다. 처음 CP949는 KSC5601에 표현된 2350자만을 제공하였으나 KSC5601-92가 제정되면서 조합형 한글에 대한 부호표도 추가되어 제공되고 있다.

**Comment by extJo** [comment]
수고해쓰용~
