### ISSUE TITLE
week01. KimDongGeun

### ISSUE THREAD

**Issue by ehdrms2034** [Apptive-dev-10th/Node_js_Study#4]
**1. var 와 let 의 차이점 및 장단점.**
var: 전역변수와 같은 기능을 하고있으며 범위는 Function Scope이며 전역변수 오염이 일어 날 수 있음.
let: 지역변수와 같은 기능으로 block 범위로 전역변수 오염을 방지 시켜준다. let은 같은 블록범위이내에
한번만 선언이 가능하다.

**2. js 에서 this keyword 조사하기.**
javascript의 this는 4가지의 패턴이 존재한다.
1.함수 호출 패턴 : this가 전역객체를 가리키는 경우 Web Browser == windows , Node.js == grobal
2.메소드 호출 패턴 : 한 클래스의 메소드로써 object를 가리키는 경우 this == obj
3.생성자 호출 패턴 :  new와 함께 작용하며 앞에 new가 있을경우에는 객체를 생성할 때 this는 obj를 가리키게 된다.  객체 리터럴 방식과는 차이가 존재한다.
4.apply 호출 패턴 : this를 특정객체에 명시적으로 바인딩하는 방법. webbrowser의 경우 기본적으로 this는 windows를 뜻하나 이 apply를 통하여 this가 다른 객체를 향하도록 변경할 수 있는 것

**3. callback function 또는 callback 이 무엇인지 조사하기.**
콜백(callback)은 다른 코드의 인수로서 넘겨주는 실행 가능한 코드를 말한다
필요성은 자바 스크립트의 경우 비동기성을 띄고있기 때문에 동기적인 요청이 필요할 때 이 콜백함수를 주로 많이 사용한다.
그래서 동기적인 요청이 많이 필요한 경우 흔히들 콜백 지옥에 빠진다고들 한다.
대안법으로는 promise then 혹은 async await 등이 있다.

**4. MIME Type 에 대해서 조사하기**
Multiplepurpose Internet Mail Extensions의 약어로
메시지의 내용이 어떤 형식인지 알려주기 위해 정의한 인터넷 표준.
메시지의 내용으로는 일반 텍스트, 이미지, 오디오, 비디오 등이 들어갈 수 있으며 이러한 형식을 간단한 값으로 표현.

text/plain : 일반 텍스트 문서
text/html : html 문서
text/css : css 문서
text/xml : xml 문서
image/jpeg : jpeg파일
image/png : png파일
audio/mpeg : mpeg 파일
audio/ogg : ogg파일
audio/* : audio 파일
video/mp4 : mp4파일
application/zip : zip 압축파일
등등이 존재한다.

**5. character encoding 종류에 대해서 조사하기.**
 1.ascii 2.ansi 3.utf가 크게 있다.
ascii는 영어를 표현하기 위해 128비트로 이루어진 문자인코딩 타입이며
1비트당 각각이 대응하는 단어가 있기 때문에 2바이트로 이루어진 한국어는 불가

ansi는 영어이외의 단어를 표현하기 위한 인코딩 타입 (ex: EUC-kr 한국식 ansi타입)
단 한국어 영어 이외에는 다른 글자 언어를 포함 X

UTF 유니코드라고 불리며 국가의 모든 언어를 표현하기 위한 문자 인코딩 타입
최근 유니코드에선 한국어를 표현하기 위해서는 2byte에서 3byte표현으로 늘어났다고한다.

**Comment by extJo** [comment]
굳굳
