### ISSUE TITLE
week1_KimJaeIn

### ISSUE THREAD

**Issue by BM-Jake** [Apptive-dev-10th/Node_js_Study#5]
1. var와 let의 차이점 및 장단점.

	var는 변수에 A할당하고 난 후 같은 변수에 B할당해도 에러 발생X (중복 선언 가능)

	let은 변수에 A할당하고 난 후 같은 변수에 B할당해도 에러 발생O
------------------------------------------------------------------------
	var는 정의 되지 않은 변수 호출 후, var로 변수 선언하면 그 변수는 
	형(type)이 undefined 되어 있을 뿐 정상적으로 작동한다. 이건 Hoisting이라 그럼

	let는 정의 되지 않은 변수 호출 후, let로 변수 선언하면 호출한 시점에서
	변수가 선언되어 있지 않음을 알리는 에러가 발생.
------------------------------------------------------------------------
	var는 Function-scope여서 유효 범위가 함수 단위이다.
	
	1  var foo = 'bar1';
	2  cosole.log(foo); // bar1
 	3
	4  if (true) {
	5    var foo = 'bar2';
	6    console.log(foo); // bar2
	7  }
	8 
	9  console.log(foo); // bar2
	
	위 코드가 하나의 함수 구문 안에 존재한다고 가정했을 때, if문 밖의 변수와
	안의 변수 foo는 동일한 변수이다. 중복 선언을 했지만 별다른 에러 X,

	let은 Block-scope여서 유효 범위가 블록, 즉{}로 감싸지는 범위이다.
	
	1  let foo = 'bar1';
	2  cosole.log(foo); // bar1
 	3
	4  if (true) {
	5    let foo = 'bar2';
	6    console.log(foo); // bar2
	7  }
	8 
	9  console.log(foo); // bar1

	위 코드에서 var를 사용한 경우와는 달리 if문 밖의 변수와 안의 변수 foo는
	서로 다른 변수이다.

*2. js에서 this keyword 조사하기.

	- Javascript의 this 키워드는 Owner를 가리키는데 Object 내에 있으면 Object
	  , 그렇지 않으면 window(root)를 가리킨다.

	- call(), apply(), bind()를 통해 this가 가리키는 Owner를 바꿀 수 있다.

	- callback의 경우에는 this를 착각하기 쉽다. 주의해야 한다.

	this는 안쓰는게 최대한 좋다는 결론이 나온다.

3. callback function 또는 callback이 무엇인지 조사하기.

	callback function : 어떠한 정보(또는 이벤트)를 관리하는 대상이 자신의 정보가 변경
	되거나 또는 이벤트가 발생할때, 자신의 변경된 정보나 이벤트에 따라 어떠한 처리를 
	할 수 있도록 제공하는 함수.

	어떤 정보를 원하는 쪽이 정보를 제공하는 쪽에게 반복적으로 정보를 요구(또는 확인)하는
	방법보다 정보를 제공하는 쪽이 정보를 원하는 쪽에게 통보하는 것이 효율적
	-> 이런 상황에서 사용하면 좋은 것이 callback함수.

	무엇인가 일을 다른 객체에게 시키고, 그 일이 끝나는 것을 기다리는 것이 아니라 그 객체가
	나를 다시 부를때까지 내 할일을 하고 있는다는 개념.
	따라서 Non-Block이며, 비동기(Asynchronous)방식의 함수로 사용됨.
	함수 속에서 또 다시 function콜을 한다.
	
	특정 이벤트가 발생하기 전에는 프로그램 입장에서 이벤트의 정보를 사용자에게 알려줄 수도
	없습니다. 그렇다고 개발자가 개발시에 사용자에게 알려줄 이벤트가 언제 발생할지도 모르죠.
	이런 경우 이벤트 발생시 데이터를 전달하게 끔 Callback을 이용하여 구현하는 것임.
	
	이 함수는 다른 함수의 매개변수로 호출될 함수를 전달하고, 특정 이벤트가 발생하고 나서 
	매개변수로 호출된 함수가 다시 호출되는 것을 의미.

4. MIME Type에 대해서 조사하기.

	MIME Type이란 클라이언트에게 전성된 문서의 당양성을 알려주기 위한 메커니즘이다.
	
	웹에서 파일의 확장자는 별 의미가 X. 그러므로, 각 문서와 함께 올바른 MIME Type을
	전송하도록, 서버가 정확히 설정하는 것이 중요. 브라우저들은 리소스를 내려받았을 때
	해야 할 기본 동작이 무엇인지 결정하기 위해 대게 MIME Type을 사용.

	- 구조
	type/subtype
	MIME 타입의 구조는 매우 간단합니다; '/'로 구분된 두 개의 문자열인 타입과 서브타입으로 구성됩니다.
	스페이스는 허용되지 않습니다. type은 카테고리를 나타내며 개별(discrete) 혹은 멀티파트 타입이 
	될 수 있습니다. subtype 은 각각의 타입에 한정됩니다.
	MIME 타입은 대소문자를 구분하지는 않지만 전통적으로 소문자로 쓰여집니다.
	
	- 개별 타입

	타입	  설명						일반적인 서브타입 예시
	--------------------------------------------------------------------------------------------------------
	text	텍스트를 포함하는 모든 문서를 나타내며 		text/plain, text/html, text/css, text/javascript
		이론상으로는 인간이 읽을 수 있어야 합니다	
	
	image	모든 종류의 이미지를 나타냅니다. 		image/gif, image/png, image/jpeg
		(animated gif처럼) 애니메이션되는 이미지가 	, image/bmp, image/webp
		이미지 타입에 포함되긴 하지만, 
		비디오는 포함되지 않습니다.	
	
	audio	모든 종류의 오디오 파일들을 나타냅니다.		audio/midi, audio/mpeg, audio/webm
								, audio/ogg, audio/wav
	
	video	모든 종류의 비디오 파일들을 나타냅니다.		video/webm, video/ogg

	application	모든 종류의 이진 데이터를 나타냅니다.	application/octet-stream,  application/pkcs12
								,application/vnd.mspowerpoint, application/xhtml+xml
								, application/xml,  application/pdf
	
	
	- 멀티파트 타입(:합성된 문서를 나타내는 방법)
	
	multipart/from-data : HTMLForms과 POST 메서드의 관계속에서 사용

	multipart/byteranges : 전체 문서의 하위 집합만을 정송하기 위한 206 Partical Content 상태 메시지와 함께 사용

5. character encoding 종류에 대해서 조사하기.

	▶문자셋(Charset)
		
	- 정보를 표현하기 위한 글자들의 집합
	- 집합 안의 문자들에 음수가 아닌 정수들을 배정한 것을 부호화된 문자 집합
		(coded character set,CCS)
	- 문자 집합은 ASCII와 같이 더 이상의 문자가 추가될 수 없기도하고, 유니코드와 같이 문자가 계속  추가될 수 있기도 하다.

	▶문자인코딩 (Character Encoding)

	- 문자들의 집합을 컴퓨터에서 저장하거나 통신에 사용할 목적으로 부호화하는 방법
	- 특정한 문자 집합 안에 문자들을 컴퓨터 시스템에서 사용할 목적으로 일정한 범위 안의 정수(코드값)들로 변환하는 방법이다.

	
	▶종류

	- 영문 문자 인코딩
	영문 알파벳 26자와 숫자, 기호, 특수문자등 128자를 7비트의 이진수로 부호화한 ASCII(American Standard Code for InFormation
	Interchange)부호가 현재도 널리 사용되고 있으며, 실질적인 영문자의 국제 표준 부호이다.

	- 한글 문자 인코딩
	완성형(KSC5601-87)
		-ISO-2022(2바이트 이상의 문자 부호를 사용할 때 지켜야 하는 확장 방법에 관한 국제 표준)에 따르고 있으므로 
		  외국의 네트워크나 SW 사용에 유리하다.
		-현재의 한글 사용 실태를 조사해 보았을 때 2,350자의 한글만으로도 충분히 모든 표현이 가능하다.
		-정렬 작업에 있어서 한글 변환 테이블을 통해서 가능함으로 크게 문제가 될 것이 없다.
	

	문제점 많아서 지금은 KSC5601 완성형과 함께 조합형 한글을 함께 수용할 수 있는
	KSC5601-92를 표준으로 제정하여 현재까지 사용

	- 유니코드(Unicode) 프로젝트
	유니코드는 전세계의 모든 문자를 동일하게 표현하기 위한 산업표준으로 유니코드협회(Unicode Consortium)가 제정하며
	, 유니코드에는 ISO-10646에 포함된 문자집합, 문자 부호화와 문자를 표시하기 위한 복호화 알고리즘이 포함되어 있습니다.
	ISO-10646은 문자 표시에 관한 국제 표준으로 초기 ISO-10646과 유니코드는 서로 다른 독자적인 표준이었으나.
	ISO-10646-1이 제정되면서, ISO실행위원회와 유니코드컨소시엄의 협의로 문자 표시 방법이 통합되어 현재의 국제 표준은 
	유니코드라고 할 수 있습니다.
	(ISO-10646에는 KS X 1001(KSC5601), EUC-KR, ISO-2022-KR의 한글 문자 부호가 포함되어 있다.)

	- EUC
	euc는 extend unix code의 약자로 유닉스에서 영어를 제외한 문자를 표시하기 위한 확장 부호를 의미합니다.
	그 중 euc-kr은 한글 표현을 위한 문자 인코딩인데, 영문은 KSC5636(ASCII와 동일하나 역슬래쉬를 원표시로 대체)으로 
	처리하고 한글은 KSC5601로 처리합니다. 과거 euc-kr은 KSC5601-87의 완성형 한글이었으나 현재의 euc-kr은 KSC5601-92로 
	조합형 한글까지 사용 가능합니다.

	- CP949
	마이크로소프트에서 사용하는 한글 문자의 부호표입니다. 본래 code page는 IBM에서 최초 고안하였으나 MS-window에서 한글 표현을
	위해 채용하면서 MS949로 불리우기도 합니다. 처음 CP949는 KSC5601에 표현된 2350자만을 제공하였으나 KSC5601-92가 제정되면서 
	조합형 한글에 대한 부호표도 추가되어 제공되고 있습니다.

	- KSC5601 vs EUC-KR vs CP949
	KSC5601은 완성형과 조합형의 모든 한글 문자의 표현이 가능한 한글 문자 부호 표준이며 euc-kr과 CP949는 모두 이 KSC5601을 
	기본으로 한 문자 부호입니다. 유닉스계열의 한글 문자 부호인 euc-kr에서는 KSC5601을 그대로 수용하고 있으며, 윈도우계열 한글 
	문자 부호인 CP949(MS949)는 완성형 한글의 형태를 취하고 있으나 KSC5601에 의해 조합형으로 만들어지는 한글의 코드까지도 제공하고 
	있으므로 두 문자 부호의 인코딩 방식은 달라도 같은 코드를 만들어 내게 되어 두 문자 부호는 서로 호환됩니다. 
	단, java환경에서는 euc-kr이 KSC5601-87로 사용되어 CP949의 확장 완성형과 호환되지 않을 수도 있으니 주의해야 합니다.

	- KSC5601 vs Unicode
	유니코드에는 KSC5601의 문자 집합이 포함되어 있지만, 4byte의 유니코드의 어느 범주에 속하느냐에 따라 그리고 어떤 변환식을 
	사용하느냐에 따라 부호의 값이 달라지므로 KSC5601을 그대로 사용하는 euc-kr(CP949)와 유니코드는 서로 호환되지 않습니다.

	- 결론
	현재의 한글 표준 부호는 완성형과 조합형의 구분이 없습니다, euc-kr로 선언된 웹페이지에서든, MS949를 사용하는 윈도우에서든 
	똠, 꿿, 휗 휅 같은 문자들이 모두 표시가 되기 때문에 한글을 더 쉽게 사용할 수 있어, 국제표준인 유니코드와 유닉스계열의 euc-kr만 
	잘 구분하여 사용할 수 있으면 인코딩 때문에 한글이 깨지는 일은 없을 것 입니다.

**Comment by extJo** [comment]
굳
