### ISSUE TITLE
Week1 Lee Gyo Won

### ISSUE THREAD

**Issue by Gyogle** [Apptive-dev-10th/Node_js_Study#6]
1. var와 let의 차이점 및 장단점.
  - var : function-scoped단위로 hoisting, 재선언, 변수 선언때문에 너무 많은 일들을 해야 함.
  - let : block-scoped단위로 hoisting, 재선언 불가능, 재할당 가능
  - const : 재선언 불가능, 재할당 불가능

// let
let a = 'test'
let a = 'test2' // Uncaught SyntaxError: Identifier 'a' has already been declared
a = 'test3'     // 가능

// const
const b = 'test'
const b = 'test2' // Uncaught SyntaxError: Identifier 'a' has already been declared
b = 'test3'    // Uncaught TypeError:Assignment to constant variable.

2. js에서 this
  - strict mode에서 함수를 정의하는 경우, this는 undefined
  - 웹브라우저에서는 window 객체, 실행문맥, 호출객체를 의미함.
  - 명시적으로 this를 바꾸는 함수 : bind, call, apply
  - 엄격 모드 : 코드 안정성과 나은 오류 검증을 위해 ECMA Script 5.1버전에서 제공
               작성을 위해 함수 내부의 최상단에 'use strict'라는 예약어를 적음.
               this를 undefined로 만들고, 실행 문맥은 더이상 전역객체로 되지 않음.

3. callback function
  - 단순하게는 함수의 호출 실행 시점을 프로그래머가 아닌 시스템에서 결정하는 함수를 콜백함수라고 한다.
  - 코드 상에 존재하더라도, 프로그래머가 별도로 호출을 시도하지 않아도, 시스템이 결과를 가지고 함수를 호출하고 처리한 후, 넘겨준다.

4. MIME Type(Multipupose Internet Mail Extensions)
  - 클라이언트에게 전송된 문서의 다양성을 알려주기 위한 메커니즘.
  - 메시지 컨텍트 형식을 정의하기 위한 인터넷 표준.
  - 메시지에는 텍트스, 이미지, 오디오, 비디오 및 어플리케이션의 특정 데이터를 포함 가능하며 일반적으로 홈페이지상에 표현되는 멀티미디어 데이터에 대한 형식을 말함.
  - 클라이언트의 웹브라우저나 사이트를 제공하는 웹 서버에서 MIME Type이 등록되지 않는다면 User는 해당 컨텍트를 웹브라우저에서 볼수 없음.

5. character encoding
  - UNICODE : 유니코드, 문자열을 숫자로 표현하기 위해, 문자와 숫자를 각각 매핑한 것(매핑=사상)
  - UTF-8 : 유니코드 인코딩의 하나로, 문자열을 8-bit기반으로 저장, ANSI문자는 1Byte, 아시아 문자는 3Byte로 가변표기 인코딩 방식.
            조합형 인코딩 방식, 한글의 편리함을 그대로 가지고 있음, 초,중,종성으로 구분하여 문자를 작성
  - EUC-KR : 완성형 인코딩 방식, 한글을 2바이트로 사용하는 문자집합, 단 한글을 사용하는 곳에서만 제대로 문자가 보임. 하나의 완성된 글자로 인식, 유니코드보다 확장성이 떨어지며, 만약에 글자표에 없는 글자 인식시 □로 표시됨.
	     KS X 1001와 KS X 1003을 사용하는 8비트 문자 인코딩으로, EUC의 일종이며 대표적인 한글 완성형 인코딩이기 때문에 보통 완성형이라고 불린다.
  - CP949 : EUC-KR의 확장, EUC-KR보다 더 많은 한글을 표현할 수 있으며, 윈도우에서 주로 쓰이는 인코딩 기법. 윈도우95부터 확장 완성형 또는 통합형 한글코드라는 명칭으로 확장되어 현대의 모든 한글을 수용
     * 현재는 웹에서 UTF-8을 기본으로 사용하고 있어서 웬만한 한글 사이트를 만드는 경우에는 인코딩을 EUC-KR로 설정해야함. 윈도우 사용자가 많으므로, 정상적인 사용을 위해서 EUC-KR로 인코딩하는 것이 적합

**Comment by extJo** [comment]
굳
