### ISSUE TITLE
week02_HW_KimTaeHyeong

### ISSUE THREAD

**Issue by KimTaeHyeong17** [Apptive-dev-10th/Node_js_Study#7]
HTTP status code 에 대해서 자세히 알아오기
암호화 방식 종류 알아오기. + bcrypt 가 무엇인지 알아오기.
middleware 에 대해서 알아오기

1.HTTP status code
 : 특정 HTTP 요청이 성공적으로 완로되었는지 알려주는 코드. 5개의 그룹으로 나뉘어짐
    a)정보 제공 응답
    b)성공적인 응답
    c)리다이렉트
    d)클라이언트 에러
    e)서버에러

    a)정보응답
        100 Continue : 이 임시적인 응답은 지금까지의 상태가 괜찮으며 
        클라이언트가 계속해서 요청을 하거나 이미 요청을 완료한 경우에는
        무시해도 되는 것을 알려줌

        101 Switching Protocol : 이 코드는 클라이언트가 보낸 Upgrade 요청 
        헤더에 대한 응답에 들어가며 서버에서 프로토콜을 변경할 것임을 알려줌

        102 Processing : 서버가 요청을 수신했으며 이를 처리하고 있지만
        아직 제대로된 응답을 알려줄 수 없음.

    b)성공응답
        200 OK : 요청이 성공적으로 되었음(HTTP 메소드에 따라 성공의 의미 다름)
            GET : 리소스를 불러와서 메시지 바디에 전송되었음
            HEAD : 개체 헤더가 메시지 바디에 있음
            PUT(POST) : 수행 결과에 대한 리소스가 메시지 바디에 전송됨
            TRACE : 메시지 바디는 서버에서 수신한 요청 메시지 포함하고 있음

        201 Created: 요청이 성공적이었으며 그 결과로 새로운 리소스가 생성됨

        202 Accepted : 요청을 수신하였지만 그에 응하여 행동할 수 없음

    c)리다이렉션 메시지
        300 Multiple Choice : 요청에 대해서 하나 이상의 응답이 가능함
        301 Moved Permanetly : 요청한 리소스 URI가 변경되었음
        302 Found : 요청한 리소스의 URI 가 일시적으로 변경되었음
    
    d) 클라이언트 에러 응답
        400 Bad Request : 잘못된 문법으로 인하여 서버가 요청을 이해할 수 없음
        404 NOT found : 요청받은 리소스를 찾을 수 없음. 브라우저에서는 알려지지
        않은 URL
        408 Request Timeout : 요청을 한지 시간이 오래된 연결에 일부 서버가 전송

    e) 서버 에러 응답
        500 Internal Server Error : 서버가 어떻게 처리할지 모르는 상황에 처함 
        502 Bad Gateway : 게이트웨이로 작동중일때 Request 를 위한 response를 
        받을때 invaild 한 response 를 받았을때

    모든 HTTP 상태 코드는 여기에 : https://developer.mozilla.org/ko/docs/Web/HTTP/Status

=================================================================================================

    2.암호화 방식 종류 알아오기. + bcrypt 가 무엇인지 알아오기.

    현대의 암호화 알고리즘은 '평문 + KEY' 입력값으로 암호화된 문장을 얻어낸다.
    (암호 알고리즘이 노출되어도 Key 값을 알지 못하면 복호화 불가능)

    비밀번호를 입력받은 그대로 DB 에 저장하는 것은 범죄나 다름없다.
    암호화에는 크게 세가지 종류가 있는데 
    1)단방향 암호화, 2)양방향 암호화 2-1)비대칭형 암호화 2-2)대칭형 암호화

    <대칭형 vs 비대칭형>
    대칭형 암호 알고리즘은 암호화 할때 사용되는 Key값과 복호화 할때 사용되는 Key값이
    동일한 알고리즘이고, 비대칭형 암호 알고리즘은 암호화할때 사용되는 key값과
    복호화 할때 사용되는 key값이 서로 다른 알고리즘이다

    1)단방향 암호화
            const crypto = require('crypto');
            crypto.createHash('sha512').update('비밀번호').digest('base64'); // 'dvfV6nyLRRt3NxKSlTHOkkEGgqW2HRtfu19Ou/psUXvwlebbXCboxIPmDYOFRIpqav2eUTBFuHaZri5x+usy1g=='
            crypto.createHash('sha512').update('비밀번호').digest('base64'); // 위와 같은 결과
            crypto.createHash('sha512').update('비밀번호').digest('hex'); // '76f7d5ea7c8b451b773712929531ce92410682a5b61d1b5fbb5f4ebbfa6c517bf095e6db5c26e8c483e60d8385448a6a6afd9e513045b87699ae2e71faeb32d6'

        가장 간단한 방식은 해시함수를 사용하는것.
        크립토 모듈을 불러와서 createHash 메소드를 사용하면 된다. 
        인자로 사용할 sha256,sha512 같은 알고리즘을 사용함
        update 메소드에는 암호화할 비밀번호를
        digest 에는 어떤 인코딩 방식으로 암호화된 문자열을 표시할지 정함
    
    2)양방향 암호화(웹에서는 이 방식을 사용하기 힘들다)-대칭형 암호화
            const cipher = crypto.createCipher('aes-256-cbc', '열쇠');
            let result = cipher.update('암호화할문장', 'utf8', 'base64'); // 'HbMtmFdroLU0arLpMflQ'
            result += cipher.final('base64'); // 'HbMtmFdroLU0arLpMflQYtt8xEf4lrPn5tX5k+a8Nzw='

            const decipher = crypto.createDecipher('aes-256-cbc', '열쇠');
            let result2 = decipher.update(result, 'base64', 'utf8'); // 암호화할문 (base64, utf8이 위의 cipher과 반대 순서입니다.)
            result2 += decipher.final('utf8'); // 암호화할문장 (여기도 base64대신 utf8)
        
        createCipher로 암호화 객체를 만든다
        update(암호화할 문장) 및 final 메소드를 호출시 암호화 진행
        decipher 은  createDecipher로 복호화 객체를 만든뒤
        update(암호화된 result 값을 넣는다) 와 final 똑같이 실행

출처 :  https://www.zerocho.com/category/NodeJS/post/593a487c2ed1da0018cff95d
        https://sungjk.github.io/2016/09/30/Security.HbMtmFdroLU0arLpMflQ

2-2.bcrypt
    : Blowfish 알고리즘을 기반으로 설계한 암호화 해시 알고리즘이다.
    비밀번호를 저장하기 위한 목적으로 개발되었으며, 지금까지 사용되고 있다.
    이 알고리즘은 입력값을 72byte로 제한 한다는것이 단점이다. 이는 128byte를
    맞추기 위함인데, 이러한 제약에서 벗어나기 위해 나중에 개발된 script를 대안으로 
    사용하기도 한다.

    bcrypt 해싱 분석
    ex) $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
        앞의 4byte, $2a$는 이것이 bcrypt 알고리즘을 이용한 다이제스트라고 명시한다.
        다음 10$은 Cost를 의미한다. bcrypt는 2^(cost)번 반복하여 만들어졌다고 명시한다.
        다음 N9qo8uLOickgx2ZMRZoMye(22byte)는 이 bcrypt에 사용된 salt를 의미한다. salt는 128bit를 base64 인코딩하여 22개의 문자열을 갖는다.
        그 이후 끝까지 IjZAgcfl7p92ldGxad68LJZdL17lhWy(31byte)는 해시 결과값이다.
        따라서 salt값을 따로 저장할 필요없이 DB에는 총 128byte의 해시 문자열을 저장한다.

출처 : https://genesis9413.github.io/web_study/2017/10/08/12.html

3. middleware 에 대해서 알아오기
        운영체제와 해당 운영체제에서 실행되는 응용 프로그램 사이에 존재하는
        소프트웨어. --> 분산응용 프로그램의 통신 및 데이터 관리를 가능하게함
        소프트웨어에 관한 소프트웨어

        미들웨어의 종류 : API, 애플리케이션서버,애플리케이션 통합, 데이터 통합,
                         TP(트랜잭션 처리),RPC etc..

출처 : https://www.redhat.com/ko/topics/middleware/what-is-middleware

**Comment by extJo** [comment]
조금 아쉽지만 수고했어용
