### ISSUE TITLE
Week_02_JangYuri

### ISSUE THREAD

**Issue by JangYuri** [Apptive-dev-10th/Node_js_Study#9]
### 1. HTTP status code
 : 특정 HTTP 요청이 성공적으로 완료되었는지 알려준다. 응답은 5개의 그룹으로 나누어진다: 순서대로 1xx, 2xx, 3xx, 4xx, 5xx로 시작한다.
        1. **정보를 제공하는 응답** : 요청을 받았고, 작업을 진행 중이라는 의미이다. HTTP/1.0 이후 정의되지 않았다. 서버들도 클라이언트에게 이 코드를 보내지는 않는다. 단 101의 경우 WebSocket등에서 쓰인다.
        2. **성공적인 응답** : 이 작업을 성공적으로 받았고, 이해했으며, 받아들여졌다는 의미이다. 200과 206을 제외하고는 볼 일이 거의 없는 코드들이다.
            -  200 OK: 성공적으로 처리했을 때 쓰인다. 가장 일반적으로 볼 수 있는 HTTP 상태.
            - 206 Partial Content 컨텐츠의 일부 부분만 제공한다. 보통 클라이언트에서 시작 범위나 다운로드할 범위를 지정한 경우 자동으로 해당 부분만 제공할 때 사용하는 코드이다.
        3. **리다이렉트** : 이 요청을 완료하기 위해서는 리다이렉션이 이루어져야 한다는 의미이다. 짧은 주소(단축 URL) 서비스의 경우 접속 시 301이나 302 코드를 보내고, 헤더의 location에 리다이렉션할 실제 URL을 적어 보낸다.
        4. **클라이언트 에러** : 클라이언트 오류: 이 요청은 올바르지 않다는 의미이다. 여기서부터 브라우저에 직접 표출된다. 자주 보이는 오류는 아래와 같다.
            - 400 Bad Request: 요청 자체가 잘못되었을때 사용하는 코드이다.
            - 401 Unauthorized: 인증이 필요한 리소스에 인증 없이 접근할 경우 발생한다. 이 응답 코드를 사용할 때에는 반드시 브라우저에게 어느 인증 방식(Basic과 Digest 두가지가 있다. Basic은 아이디와 비밀번호를 평문 그대로(!) 전송하며, Digest는 아이디와 nonce값을 이용해 해시를 만들어 전송한다.)을 사용할 것인지 보내 주어야 한다. 단순히 권한이 없는 경우 이 응답 코드 대신 아래 403 Forbidden을 사용해야 한다.
            - 403 Forbidden: 서버가 요청을 거부할 때 발생한다. 관리자가 해당 사용자를 차단했거나 서버에 index.html이 없는 경우(만약 접근을 index.html까지 지정해서 했다면 404가 뜬다. 이건 방식의 차이인데, index.html을 지정하지 않고 접근하면 서버는 자동으로 index.html을 찾아서 띄워주고 그런 파일이 없다면 해당 디렉토리에 있는 파일 리스트를 보여주게 된다. 그러나 보안상 이유로 웹 브라우저에서 파일 리스트를 보는 권한을 백이면 백 막아놓기 때문에 접근을 거부하는 403 에러를 띄우게 된다. 그러나 파일까지 지정해서 접근하면 서버는 파일로 바로 접근하기 때문에 파일이 없다는 404 에러를 띄우는 것이다.)에도 발생할 수 있다. 혹은 권한이 없을 때(로그인 여부와는 무관하다)에도 발생한다.
            - 404 Not Found: 찾는 리소스가 없다는 뜻이다.
            - 408 Request Timeout : 요청 중 시간이 초과되었을때 사용하는 코드이다.
        5. **서버 에러** : 올바른 요청에 대해 서버가 응답할 수 없다는 의미이다.
            - 500 Internal Server Error: 서버에 오류가 발생해 작업을 수행할 수 없을 때 뜬다. 보통 설정이나 퍼미션 문제. 아니면 HTTP 요청을 통해 호출한 문서가 실제 HTML 문서가 아니라 JSP, PHP, 서블릿 등의 프로그램일 경우 그 프로그램이 동작하다 세미콜론 빼먹는 등의 각종 에러로 비정상종료하는경우 이 응답코드를 보낸다.
            - 502 Bad Gateway: 게이트웨이가 잘못 되었을 때 나온다.
            - 503 Service Temporarily Unavailable: 서버를 현재 일시적으로 사용할 수 없을 때 뜬다. 유지보수중이거나, 터졌거나 할 때 발생함.
            - 504 Gateway Timeout
            - 520 Unknown Error: 말 그대로 알 수 없는 오류.

### 2. 암호화 방식 종류 알아오기.
	1. **대칭형 암호** (비밀키 암호) : 암호화 키와 복호화 키가 같다. 
            - 현재 가장 보편적으로 쓰이는 암호화 방식은 현 미국 표준 방식인 AES이다. 
	2. **비대칭형 암호** (공개키 암호) : 암호화키와 복호화키다 다르다.
            - 암호화를 하면 하나의 키 쌍이 생기고, 두 개의 키를 각각 키 A, 키 B라고 했을 때 키 A로 암호화한 암호문은 키 B로만 복호화할 수 있고 키 B로 암호화한 암호문은 키 A로만 복호화할 수 있다. 따라서 이 중 하나의 키만 비밀로 보호하고(이를 '비밀키', '개인키'라고 한다) 다른 하나의 키는 공중에게 공개해도 관계가 없다(이를 '공개키'라고 부른다). 이렇게 둘 중 하나의 키는 반드시 공개되어야 통상적인 사용이 가능하므로 공개키 암호방식이라고 한다.

대칭형 암호는 훌륭한 암호화 방식이기는 하지만 결정적인 문제가 존재한다. 바로 '키 배송'에 관한 문제로, 어떻게든 송신 측에서는 수신 측에 암호 키를 전달해야만 하고, 이 키가 배송 과정에서 털리면 아무리 뛰어난 암호화 알고리즘을 사용했더라도 속절없이 평문이 털리게 된다. 안전하게 평문을 전달하기 위해 만든 것이 암호문인데, 정작 키는 안전하게 전달할 방법이 없는 것. 이 키 배송에 대한 방법은 여러 가지 방법이 연구되었지만 발상의 전환으로 키 배송 문제를 해결한 방식이 비대칭형 암호방식이다.

한데 비대칭형 암호는 암/복호화가 대칭형 암호에 비해 현저하게 느리다는 문제점이 있다. 따라서 현실적으로는 비대칭형 암호를 이용해서 대칭형 암호의 키를 배송하고 실제 암호문은 대칭형 암호를 사용하는 식으로 상호보완적으로 이용하는 것이 일반적이다.
	3. **단방향 암호**
            - 해싱(hashing)을 이용해 암호화를 하는 것으로 암호화(encyrption)/복호화(decryption) 와는 다른 개념이다.
            - 해싱을 이용해 평문을 암호문으로 암호화하는 것은 가능하지만 암호문을 평문으로 복호화 하는것은 불가능하다.

패스워드는 양방향 암호로 저장하는 것보다 단방향 암호로 저장하는 것이 안전하다. 암호화된 패스워드 목록이 유출된다고 해도 이를 가지고 원래의 패스워드를 복원할 수 없고, 패스워드 자체를 검증할 때는 입력받은 값을 암호화해서 암호화한 값끼리 비교하면 문제가 없기때문이다.

MD5, SHA 같은 방식이 있지만 MD5는 단시간 내에 충돌값을 찾아낼수 있기 때문에 현재는 SHA-2, 가능하면 SHA-3를 쓰는 것이 좋다.

### * BCrypt
    - 패스워드 암호화에 특화된 password hashing function이다.
    - salt값을 따로 DB에 저장하지 않는다.
    - 활용하는 메소드는 아래와 같다.
        * Bcrypt.hashpw(password, salt)를 이용하여 패스워드를 해시한다.
        * Bcrypt.checkpw(password, hashed)를 이용하여 패스워드를 비교한다.
    - BCrypt 사용 예 
```
// 사용자의 비밀번호 
String password = "!@#$password1234";
 // 위 비밀번호의 BCrypt 알고리즘 해쉬 생성, passwordHashed 변수는 실제 데이터베이스에 저장될 60바이트의 문자열이 된다. 
String passwordHashed = BCrypt.hashpw(password, BCrypt.gensalt());
 // 위 문장은 아래와 같다. 숫자가 높아질수록 해쉬를 생성하고 검증하는 시간은 느려진다. 즉, 보안이 우수해진다. 하지만 그만큼 응답 시간이 느려지기 때문에 적절한 숫자를 선정해야 한다. 기본값은 10이다. 
String passwordHashed = BCrypt.hashpw(password, BCrypt.gensalt(10)); 
// 생성된 해쉬를 원래 비밀번호로 검증한다. 맞을 경우 true를 반환한다. 주로 회원 로그인 로직에서 사용된다. 
boolean isValidPassword = BCrypt.checkpw(password, passwordHashed);
```

### 3. middleware 
 : 미들웨어는 운영 체제에서 제공되지 않는 서비스를 애플리케이션에 제공하는 다목적 소프트웨어이다. 커널과 사용자 애플리케이션 사이에 있는 모든 소프트웨어를 미들웨어로 분류할 수 있다. 애플리케이션에 들어온 요청을 필터링할수 있는 기능을 제공한다. 애플리케이션보다 먼저 실행시킬 수 있으므로 인증 여부 확인등 공통 기능을 편리하게 구현할 수 있다.
    - 종류
        1. API((애플리케이션 프로그래밍 인터페이스)
        2. 애플리케이션 서버
        3. 애플리케이션 통합
        4. 데이터 통합
        5. TP(트랜잭션 처리)
        6. RPC(원격 프로시저 호출)
        7. MOM(메시지 중심 미들웨어)
        8. ORB(오브젝트 리퀘스트 브로커)
    - 용도
        * RedirectIfAuthenticated : 위에서 설명한 인증 여부를 확인하고 인증되지 않았을 경우 인증 페이지로 redirect 한다.
        * Authenticate: 사용자 인증을 처리하는 미들웨어다.
        * EncryptCookies: 보안을 위해 쿠키를 암호화한다.
        * VerifyCsrfToken: 사이트 간 요청 위조(CSRF 또는 XSRF; Cross-Site Request Forgery) 공격 방지를 위해 자동으로  CSRF 토큰을 검증하며 자세한 내용은 아래에서 다룬다.
        * CheckForMaintenanceMode:  매 요청시마다 사이트가 정비 모드인지 확인한다.

**Comment by extJo** [comment]
좋아여~~~ 고생했숩니당
